plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.exmachina.ndicamerastreamer'
    compileSdk 33
    ndkVersion "27.0.12077973"

    defaultConfig {
        applicationId "com.exmachina.ndicamerastreamer"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "0.1"

        ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64'
        }

        externalNativeBuild {
            cmake {
                cppFlags '-std=c++17'
            }
        }
    }

    externalNativeBuild {
        cmake {
            path 'src/main/cpp/CMakeLists.txt'
            version '3.22.1'
        }
    }

    buildTypes {
        debug { debuggable true }
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "ndi-camera-streamer.apk"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
